language: node_js
node_js:
  - "0.10"

before_install:
  - git submodule update --init --recursive

install:
  - npm install

before_script:
  - npm install -g grunt-cli
  - npm install -g npm@2.14

script:
  - grunt test

notifications:
  email:
    on_success: never
    on_failure: change
