---
javascripts:
- base:
  - plugins/jquery.min
  - plugins/general_functions
- dashboard:
  - plugins/tumblr
  - plugins/jquery.color
  - admin/tables/dashboard
  - admin/tables/import
- public_tables:
  - plugins/tumblr
  - plugins/jquery.color
  - admin/tables/public_tables
  - admin/tables/import
- table:
  - plugins/jquery.mousewheel
  - plugins/jscrollpane.min
  - plugins/jquery.color
  - plugins/jquery.scrollTo
  - plugins/jquery.livequery.min
  - plugins/tag-it
  - admin/table/loading_messages
  - admin/table/loader_queue
  - admin/table/carto_table
  - admin/table/out_table_elements
  - admin/maps/maps
  - admin/table/geocoding
  - admin/table/worker_geocoding
  - admin/table/table

stylesheets:
- base:
  - reset
- home:
  - front/home
- sessions:
  - front/sessions
- dashboard:
  - admin/layout
  - admin/tables/dashboard
- public_tables:
  - admin/layout
  - admin/tables/public_tables
- table:
  - admin/table/out_table_elements
  - admin/table/carto_table
  - admin/maps/maps