package_assets: on
compress_assets: on
embed_assets: off
javascripts:
  common:
    - public/js/vendor/jquery.min.js
    - public/js/rails.js

  cdbjsvendor:
    - public/js/lib/cdb.js/vendor/**/*.js

  cdbjs:
    - public/js/lib/cdb.js/src/**/*.js

  dashboard:
    - public/js/lib/cartodb/app.js
    - public/js/lib/cartodb/models/**/*.js
    - public/js/lib/cartodb/dashboard/dashboard.js

stylesheets:
  common:
    - public/css/fonts.css
    - public/css/sprites.css
    - public/css/core.css
    - public/css/buttons.css
    - public/css/header.css
    - public/css/subheader.css
    - public/css/tables.css
    - public/css/footer.css
    - public/css/leaflet.css
