package_assets: on
compress_assets: on
embed_assets: off
javascripts:
  common:
    - public/js/vendor/jquery.min.js
    - public/js/rails.js
    - public/js/vendor/underscore-min.js
    - public/js/vendor/backbone.js
    - public/js/vendor/leaflet.js

  cartodb:
    - public/js/lib/cartodb.js
    - public/js/lib/core/**/*.js
    - public/js/lib/geo/**/*.js
    - public/js/lib/ui/**/*.js

  dashboard:
    - public/js/lib/cartodb/app.js
    - public/js/lib/cartodb/models/**/*.js
    - public/js/lib/cartodb/dashboard/dashboard.js

stylesheets:
  common:
    - public/css/core.css
    - public/css/fonts.css
    - public/css/header.css
    - public/css/subheader.css
    - public/css/tables.css
    - public/css/footer.css
    - public/css/sprites.css
    - public/css/leaflet.css
