package_assets: on
compress_assets: on
embed_assets: off
javascript_compressor: uglifier
javascripts:

  common:
    - public/js/lib/cdb.js/vendor/jquery.min.js
    - public/js/vendor/jquery.tipsy.js
    - public/js/rails.js

  cdbjs:
    - public/js/lib/cdb.js/vendor/underscore-min.js
    - public/js/lib/cdb.js/vendor/backbone.js
    - public/js/lib/cdb.js/vendor/leaflet.js
    - public/js/lib/cdb.js/vendor/wax.leaf.js
    - public/js/lib/cdb.js/vendor/cartodb-leaflet.js
    - public/js/lib/cdb.js/src/cartodb.js
    - public/js/lib/cdb.js/src/core/**/*.js
    - public/js/lib/cdb.js/src/ui/**/*.js
    - public/js/lib/cdb.js/src/geo/map.js
    - public/js/lib/cdb.js/src/geo/**/*.js
    - public/js/lib/cartodb/app.js

  dashboard:
    - public/js/vendor/d3.v2.js
    - public/js/vendor/fileuploader.js
    - public/js/lib/cartodb/models/**/*.js
    - public/js/lib/cartodb/common/**/*.js
    - public/js/lib/cartodb/dashboard/**/*.js
    - public/js/lib/cartodb/dashboard/dashboard.js
    - public/js/lib/cartodb/**/*.jst
    - public/js/vendor/moment.js

  keys:
    - public/js/vendor/ZeroClipboard.js
    - public/js/lib/cartodb/models/**/*.js
    - public/js/lib/cartodb/common/**/*.js
    - public/js/lib/cartodb/keys/**/*.js
    - public/js/lib/cartodb/keys/keys.js
    - public/js/lib/cartodb/**/*.jst

  table:
    - public/js/lib/cartodb/models/**/*.js
    - public/js/lib/cartodb/common/**/*.js
    - public/js/lib/cartodb/table/**/*.js
    - public/js/lib/cartodb/table/table.js
    - public/js/lib/cartodb/**/*.jst

  login:
    - public/js/vendor/modernizr-min.js
    - public/js/vendor/selectivizr-min.js
    - public/js/lib/cartodb/app.js
    - public/js/lib/cartodb/login/placeholder.js
    - public/js/lib/cartodb/login/error.js
    - public/js/lib/cartodb/login/login.js

  specs:
    - public/js/lib/test/lib/jasmine-1.2.0/jasmine.js
    - public/js/lib/test/lib/jasmine-1.2.0/jasmine-html.js
    - public/js/lib/test/lib/sinon-1.3.4.js
    - public/js/lib/test/spec/SpecHelper.js
    - public/js/lib/test/spec/**/*.js

stylesheets:
  specs:
    - public/js/lib/test/**/*.css

  common:
    - public/css/vars.css
    - public/css/helpers.css
    - public/css/fonts.css
    - public/css/sprites.css
    - public/css/core.css
    - public/css/buttons.css
    - public/css/block.css
    - public/css/custom_objects.css
    - public/css/copy.css
    - public/css/tipsy.css
    - public/css/dropdown.css
    - public/css/modal.css
    - public/css/keys.css
    - public/css/flash.css
    - public/css/header.css
    - public/css/subheader.css
    - public/css/tables.css
    - public/css/footer.css
    - public/css/table.css
    - public/css/table_panel.css
    - public/css/map.css
    - public/css/leaflet.css
    - public/css/background_importer.css
    - public/css/privacy_selector.css
    - public/css/infowindow.css
    - public/css/floating.css
    - public/css/create_dialog.css
    - public/css/dialog_small_edit.css
