---
javascripts:
- base:
  - jquery.min
- dashboard:
  - plugins/jquery.color
  - admin/dashboard
  - admin/import
- public_tables:
  - plugins/jquery.color
  - admin/public_tables
- table:
  - plugins/jquery.mousewheel
  - plugins/jscrollpane.min
  - plugins/jquery.scrollTo
  - plugins/jquery.livequery.min
  - plugins/tag-it
  - admin/loader_queue
  - plugins/cDBtable
  - admin/table_elements
  - admin/table

stylesheets:
- base:
  - reset
- home:
  - front/home
- sessions:
  - front/sessions
- dashboard:
  - admin/dashboard
- public_tables:
  - admin/public_tables
- table:
  - admin/table
  - admin/cDBtable
