cartodb_errors:
  unknown_error:
    code: 0
    message: "We're sorry, an error has occurred"
    hint: "For help, please <a href='http://support.cartodb.com/discussion/new'>contact our support team</a> who will be happy to assist."
  empty_file:
    code: 1
    message: The file you have tried to upload has no data
    hint: "In order to create a table from importing a file, the file must have data"
  unrecognized_format:
    code: 2
    message: The file you are trying to upload has an invalid format
    hint: "Please note that supported formats are: CSV, XLS, SHP & ZIP"
  geometries_error:
    code: 3
    message: An error has occurred when importing geometry
    hint: ""
  url_error:
    code: 4
    message: An error has occurred when importing a URL
    hint: "Please note that supported formats are: CSV, XLS, SHP & ZIP "    