cartodb_errors:
  unknown_error:
    code: 0
    message: An error has occurred
    hint: "To help us investigate, please <a href='http://support.cartodb.com/discussion/new'>submit</a> a detailed description of your actions that lead to this message. Thank you for your help!"
  empty_file:
    code: 1
    message: The file you have tried to upload has no data
    hint: "In order to create a table from importing a file, the file must have data"
  unrecognized_format:
    code: 2
    message: The file you are trying to upload has an invalid format
    hint: "Supported formats are: CSV, XLS, SHP, ZIP"
  geometries_error:
    code: 3
    message: An error has occurred when importing geometry
    hint: ""